liupicrm/liupiapp/urls.py
from django.conf.urls import url
from liupiapp import views
from rbac.rbac_view import login_reg
urlpatterns = [
    url(r'^reg/', views.reg,name='reg'),
url(r'^login/', login_reg.login,name='login'),
url(r'^index/', login_reg.index,name='index'),
url(r'^add_customer/', views.add_customer,name='add_customer'),
url(r'^edit_customer/(\d+)/', views.add_customer,name='edit_customer'),
# url(r'^my_customer/', views.index,name='my_customer'),
url(r'^del_abc/', views.del_abc,name='del_abc'),
url(r'^add_my_customer/', views.add_my_customer,name='add_my_customer'),
url(r'^del_my_customer/', views.del_my_customer,name='del_my_customer'),
url(r'^piliang/', views.piliang,name='piliang'),
# url(r'^mohu/', views.index,name='mohu'),
    url(r'^customer_list/', views.CustomerList.as_view(), name='customer_list'),
    url(r'^my_customer/', views.CustomerList.as_view(), name='my_customer'),
url(r'^add_gerenjinjilu/$', views.add_gerenjinjilu, name='add_gerenjinjilu'),

url(r'^genjinjilu_lis/$', views.genjinjilu_lis, name='genjinjilu_lis'),
url(r'^edit_gerenjinjilu/(?P<customer_id>\d+)/', views.add_gerenjinjilu, name='edit_gerenjinjilu'),


url(r'^my_baoming_lis/', views.baoming_lis, name='my_baoming_lis'),
url(r'^baoming_lis/(\d+)/', views.baoming_lis, name='baoming_lis'),
url(r'^add_baoming_lis/(\d+)/$', views.add_baoming_lis, name='add_baoming_lis'),
url(r'^edit_baoming_lis/(?P<customer_id>\d+)/', views.add_baoming_lis, name='edit_baoming_lis'),
url(r'^classlist_lis/', views.classlist_lis, name='classlist_lis'),
url(r'^add_class_lis/', views.add_class_lis, name='add_class_lis'),
url(r'^edit_class_lis/(\d+)/', views.add_class_lis, name='edit_class_lis'),
url(r'^courserecord_lis/', views.courserecord_lis, name='courserecord_lis'),
url(r'^edit_courserecord/(\d+)$', views.add_courserecord, name='edit_courserecord'),
url(r'^add_courserecord/$', views.add_courserecord, name='add_courserecord'),
url(r'^studyrecord_lis/(\d+)/', views.studyrecord_lis, name='studyrecord_lis'),
url(r'^multi_init/', views.multi_init, name='multi_init'),

]

liupicrm/liupicrm/urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
url(r'^crm/', include('liupiapp.urls'), name='crm'),

]

liupicrm/liupiapp/models.py
from django.db import models
from multiselectfield import MultiSelectField
from django.utils.safestring import mark_safe

course_choices = (('Linux', 'Linux中高级'),
                  ('PythonFullStack', 'Python高级全栈开发'),)

class_type_choices = (('fulltime', '脱产班',),
                      ('online', '网络班'),
                      ('weekend', '周末班',),)

source_type = (('qq', "qq群"),
               ('referral', "内部转介绍"),
               ('website', "官方网站"),
               ('baidu_ads', "百度推广"),
               ('office_direct', "直接上门"),
               ('WoM', "口碑"),
               ('public_class', "公开课"),
               ('website_luffy', "路飞官网"),
               ('others', "其它"),)

enroll_status_choices = (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))

seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
                       ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'),)
pay_type_choices = (('deposit', "订金/报名费"),
                    ('tuition', "学费"),
                    ('transfer', "转班"),
                    ('dropout', "退学"),
                    ('refund', "退款"),)

attendance_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('absence', "缺勤"),
                      ('leave_early', "早退"),)

score_choices = ((100, 'A+'),
                 (90, 'A'),
                 (85, 'B+'),
                 (80, 'B'),
                 (70, 'B-'),
                 (60, 'C+'),
                 (50, 'C'),
                 (40, 'C-'),
                 (0, ' D'),
                 (-1, 'N/A'),
                 (-100, 'COPY'),
                 (-1000, 'FAIL'),)


class Department(models.Model):
    """
    部门表
    """
    name = models.CharField(max_length=32, verbose_name="部门名称")
    count = models.IntegerField(verbose_name="人数", default=0)
    def __str__(self):
        return self.name


class UserProfile(models.Model):
    """
    用户表
    """
    username = models.EmailField(max_length=255, unique=True, )
    password = models.CharField(max_length=128)
    name = models.CharField('名字', max_length=32)
    department = models.ForeignKey('Department', default=None, blank=True, null=True)
    mobile = models.CharField('手机', max_length=32, default=None, blank=True, null=True)
    memo = models.TextField('备注', blank=True, null=True, default=None)
    date_joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Customer(models.Model):
    """
    客户表
    """
    qq = models.CharField('QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True)
    name = models.CharField('姓名', max_length=32, blank=True, null=True, help_text='学员报名后，请改为真实姓名')
    sex_type = (('male', '男'), ('female', '女'))
    sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True, null=True)
    birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)
    phone = models.BigIntegerField('手机号', blank=True, null=True)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')
    introduce_from = models.ForeignKey('self', verbose_name="转介绍自学员", blank=True, null=True)
    course = MultiSelectField("咨询课程", choices=course_choices)
    class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField("客户备注", blank=True, null=True, )
    status = models.CharField("状态", choices=enroll_status_choices, max_length=64, default="unregistered",
                              help_text="选择客户此时的状态")
    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True)
    next_date = models.DateField("预计再次跟进时间", blank=True, null=True)
    consultant = models.ForeignKey('UserProfile', verbose_name="销售", related_name='customers', blank=True, null=True, )
    class_list = models.ManyToManyField('ClassList', verbose_name="已报班级", )
    def __str__(self):
        if self.name:
            return self.name
        else:return ''

    def show_status(self):
        color_dict = {
            'signed': "green",
            'unregistered': 'red',
            'studying': 'blue',
            'paid_in_full': 'gold'
        }

        return mark_safe(
            '<span style="color: white;background: {};padding: 5px" >{}</span>'.format(color_dict.get(self.status),self.get_status_display()))

class Campus(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)

    def __str__(self):
        return self.name


class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期")
    campuses = models.ForeignKey('Campus', verbose_name="校区")
    price = models.IntegerField("学费", default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True)
    teachers = models.ManyToManyField('UserProfile', verbose_name="老师")
    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班额及类型', blank=True,
                                  null=True)
    def __str__(self):
        return self.course

    class Meta:
        unique_together = ("course", "semester", 'campuses')


class ConsultRecord(models.Model):
    """
    跟进记录表
    """
    customer = models.ForeignKey('Customer', verbose_name="所咨询客户")
    note = models.TextField(verbose_name="跟进内容...")
    status = models.CharField("跟进状态", max_length=8, choices=seek_status_choices, help_text="选择客户此时的状态")
    consultant = models.ForeignKey("UserProfile", verbose_name="跟进人", related_name='records')
    date = models.DateTimeField("跟进日期", auto_now_add=True,)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)


class Enrollment(models.Model):
    """
    报名表
    """

    why_us = models.TextField("为什么报名", max_length=1024, default=None, blank=True, null=True)
    your_expectation = models.TextField("学完想达到的具体期望", max_length=1024, blank=True, null=True)
    contract_agreed = models.BooleanField("我已认真阅读完培训协议并同意全部协议内容", default=False)
    contract_approved = models.BooleanField("审批通过", help_text="在审阅完学员的资料无误后勾选此项,合同即生效", default=False)
    enrolled_date = models.DateTimeField(auto_now_add=True, verbose_name="报名日期")
    memo = models.TextField('备注', blank=True, null=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)
    customer = models.ForeignKey('Customer', verbose_name='客户名称')
    school = models.ForeignKey('Campus')
    enrolment_class = models.ForeignKey("ClassList", verbose_name="所报班级")

    class Meta:
        unique_together = ('enrolment_class', 'customer')


class PaymentRecord(models.Model):
    """
    缴费记录表
    """
    pay_type = models.CharField("费用类型", choices=pay_type_choices, max_length=64, default="deposit")
    paid_fee = models.IntegerField("费用数额", default=0)
    note = models.TextField("备注", blank=True, null=True)
    date = models.DateTimeField("交款日期", auto_now_add=True)
    course = models.CharField("课程名", choices=course_choices, max_length=64, blank=True, null=True, default='N/A')
    class_type = models.CharField("班级类型", choices=class_type_choices, max_length=64, blank=True, null=True,
                                  default='N/A')
    enrolment_class = models.ForeignKey('ClassList', verbose_name='所报班级', blank=True, null=True)
    customer = models.ForeignKey('Customer', verbose_name="客户")
    consultant = models.ForeignKey('UserProfile', verbose_name="销售")
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)

    status_choices = (
        (1, '未审核'),
        (2, '已审核'),
    )
    status = models.IntegerField(verbose_name='审核', default=1, choices=status_choices)

    confirm_date = models.DateTimeField(verbose_name="确认日期", null=True, blank=True)
    confirm_user = models.ForeignKey(verbose_name="确认人", to='UserProfile', related_name='confirms', null=True,
                                     blank=True)


class CourseRecord(models.Model):
    """课程记录表"""
    day_num = models.IntegerField("节次", help_text="此处填写第几节课或第几天课程...,必须为数字")
    date = models.DateField(auto_now_add=True, verbose_name="上课日期")
    course_title = models.CharField('本节课程标题', max_length=64, blank=True, null=True)
    course_memo = models.TextField('本节课程内容', max_length=300, blank=True, null=True)
    has_homework = models.BooleanField(default=True, verbose_name="本节有作业")
    homework_title = models.CharField('本节作业标题', max_length=64, blank=True, null=True)
    homework_memo = models.TextField('作业描述', max_length=500, blank=True, null=True)
    scoring_point = models.TextField('得分点', max_length=300, blank=True, null=True)
    re_class = models.ForeignKey('ClassList', verbose_name = "班级")
    teacher = models.ForeignKey('UserProfile', verbose_name="讲师",related_name='t_courserecord')
    recorder = models.ForeignKey('UserProfile', verbose_name="记录者",related_name='r_courserecord')

    class Meta:
        unique_together = ('re_class', 'day_num')


class StudyRecord(models.Model):
    """
    学习记录
    """

    attendance = models.CharField("考勤", choices=attendance_choices, default="checked", max_length=64)
    score = models.IntegerField("本节成绩", choices=score_choices, default=-1)
    homework_note = models.CharField(max_length=255, verbose_name='作业批语', blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)
    note = models.CharField("备注", max_length=255, blank=True, null=True)

liupicrm/templates/add_customer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/plugins/bootstrap/css/bootstrap.css">
</head>
<body>

<div>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {% for i in for_obj %}
            <div class="col-xs-8 {% if i.errors %}has-error{% endif %}" style="position: relative">
            <div class="input-group" style="margin-top: 20px">
                <span class="input-group-addon" id="basic-addon1" ><label {% if not i.field.required %} style="color: #777777" {% endif %} for="{{ i.id_for_label }}" >{{ i.label }} : </label></span>
                {{ i }}

            </div>
            <span>{{ i.errors.0 }}</span>
            </div>
        {% endfor %}
        <button type="submit" style="position: absolute">提交</button>
    </form>

</div>
</body>
</html>

liupicrm/templates/baoming_lis.html
{% extends 'layout.html' %}


{% block content %}

    {% load my_tags %}

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">客户列表</h3>
        </div>
        <div class="panel-body">

            <div>
                <a href="{% url  'add_baoming_lis' request.user_obj.pk %}" class="btn btn-primary">新增</a>
            </div>

            <form action="" class="form-inline pull-right">
                <input type="text" name="query" class="form-control">
                <button class="btn btn-sm btn-success">搜索</button>
            </form>

            <form action="" method="post" class="form-inline">
                {% csrf_token %}
                <select name="action" id="" class="form-control">


                    {% if request.path_info == '/crm/customer_list/' %}
                        <option value="multi_apply">公户转私户</option>
                    {% else %}
                        <option value="multi_pub">私户转公户</option>
                    {% endif %}
                    <option value="multi_del">批量删除</option>

                </select>
                <button class="btn btn-sm btn-primary">应用</button>

                <table class="table table-bordered table-hover">
                    <thead>
                    <tr>
                        <th>序号</th>
                        <th>为什么报名</th>
                        <th>学完想达到的具体期望</th>
                        <th>审批通过</th>
                        <th>报名日期</th>
                        <th>备注</th>
                        <th>删除状态</th>
                        <th>客户名称</th>
                        <th>所报班级</th>
                        <th>学校</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for oj in baoming_obj_lis %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ oj.why_us }}</td>
                            <td>{{ oj.your_expectation|default:'无' }}</td>
                            <td>{{ oj.contract_approved }}</td>
                            <td>{{ oj.enrolled_date }}</td>
                            <td>{{ oj.memo }}</td>
                            <td>{{ oj.delete_status }}</td>
                            <td>{{ oj.customer }}</td>
                            <td>{{ oj.enrolment_class.course }}</td>
                            <td>{{ oj.school }}</td>


{#                            <td><a href="{% url 'edit_customer' customer.pk %}" class="btn btn-primary btn-sm">编辑</a>#}
                            <td><a href="{% url 'edit_baoming_lis' customer_id=oj.customer.pk %}" class="btn btn-primary btn-sm">编辑</a>
                                <a href="{% url 'baoming_lis' oj.customer.pk %}" class="btn btn-primary btn-sm">已报课程</a>
                            </td>

                        </tr>
                    {% endfor %}


                    </tbody>
                </table>
            </form>


            <nav aria-label="Page navigation">
                <ul class="pagination">

                    {{ page_html }}

                </ul>
            </nav>
        </div>
    </div>





{% endblock %}

liupicrm/templates/customer_list.html
{% extends 'layout.html' %}


{% block content %}

    {% load my_tags %}

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">客户列表</h3>
        </div>
        <div class="panel-body">

            <div>
                <a href="{% url  'add_customer' %}" class="btn btn-primary">新增</a>
            </div>

            <form action="" class="form-inline pull-right">
                <input type="text" name="query" class="form-control">
                <button class="btn btn-sm btn-success">搜索</button>
            </form>

            <form action="" method="post" class="form-inline">
                {% csrf_token %}
                <select name="action" id="" class="form-control">


                    {% if request.path_info == '/crm/customer_list/' %}
                        <option value="multi_apply">公户转私户</option>
                    {% else %}
                        <option value="multi_pub">私户转公户</option>
                    {% endif %}
                    <option value="multi_del">批量删除</option>

                </select>
                <button class="btn btn-sm btn-primary">应用</button>

                <table class="table table-bordered table-hover">
                    <thead>
                    <tr>
                        <th>选择</th>
                        <th>序号</th>
                        <th>ID</th>
                        <th>qq</th>
                        <th>姓名</th>
                        <th>性别</th>
                        <th>手机号</th>
                        <th>客户来源</th>
                        <th>咨询课程</th>
                        <th>班级类型</th>
                        <th>状态</th>
                        <th>下次跟进时间</th>
                        <th>销售</th>
                        <th>已报班级</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for customer in all_customer %}
                        <tr>
                            <td>
                                <input type="checkbox" name="pk" value="{{ customer.pk }}">

                            </td>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ customer.pk }}</td>
                            <td>{{ customer.qq }}</td>
                            <td>{{ customer.name|default:'无' }}</td>
                            <td>{{ customer.get_sex_display }}</td>
                            <td>{{ customer.phone }}</td>
                            <td>{{ customer.get_source_display }}</td>
                            <td>{{ customer.course }}</td>
                            <td>{{ customer.get_class_type_display }}</td>
                            <td>{{ customer.show_status }}</td>
                            <td>{{ customer.next_date }}</td>
                            <td>{{ customer.consultant.name }}</td>
                            <td>
                                {{ customer.show_class }}


                            </td>
{#                            <td><a href="{% url 'edit_customer' customer.pk %}" class="btn btn-primary btn-sm">编辑</a>#}
                            <td><a href="{% reverse_url  request  'edit_customer' customer.pk %}" class="btn btn-primary btn-sm">编辑</a>
                            </td>
                        <td><a href="{% url 'baoming_lis' customer.pk %}">报名详情</a></td>

                        </tr>
                    {% endfor %}


                    </tbody>
                </table>
            </form>


            <nav aria-label="Page navigation">
                <ul class="pagination">

                    {{ page_html }}

                </ul>
            </nav>
        </div>
    </div>





{% endblock %}

liupicrm/templates/index.html
{% extends 'muban.html' %}
{% block css %}
{% endblock %}

{% block content %}
    {% load static %}
    <link rel="stylesheet" href="/static/css/myIconfont.css">
    <div class="panel panel-primary">
        <div class="panel-heading" style="text-align: center;"><h2>STUDENT-INFO-LIST</h2></div>
        <div class="panel-body">
            <a href="/add_student/" style="color: white">
                <button type="button" class="btn btn-primary">录入学生信息</button>
            </a>
            <a href="http://127.0.0.1:8000/crm/add_customer/">添加</a>
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th>
                        <div class="editsquare" style="display: none"></div>
                    </th>
                    <th>序号</th>
                    <th style="cursor: default;">ID<em class=" NormalCss SortDescCss"></em></th>
                    <th style="cursor: default;">QQ<em class=" NormalCss SortDescCss"></em></th>
                    <th style="cursor: default;">QQ昵称<em class=" NormalCss SortDescCss"></em></th>
                    <th style="cursor: default;">性名<em class=" NormalCss SortDescCss"></em></th>
                    <th style="cursor: default;">出生日期<em class=" NormalCss SortDescCss"></em></th>
                    <th style="cursor: default;">电话<em class=" NormalCss SortDescCss"></em></th>
                    <th style="cursor: default;">来源渠道<em class=" NormalCss SortDescCss"></em></th>
                    <th style="cursor: default;">是否转介绍<em class=" NormalCss SortDescCss"></em></th>
                    <th style="cursor: default;">咨询课程<em class=" NormalCss SortDescCss"></em></th>
                    <th style="cursor: default;">班级类型<em class=" NormalCss SortDescCss"></em></th>
                    <th style="cursor: default;">客户备注<em class=" NormalCss SortDescCss"></em></th>
                    <th style="cursor: default;">状态<em class=" NormalCss SortDescCss"></em></th>
                    <th style="cursor: default;">最后跟进日期<em class=" NormalCss SortDescCss"></em></th>
                    <th style="cursor: default;">预计下次跟进状态<em class=" NormalCss SortDescCss"></em></th>
                    <th style="cursor: default;">销售<em class=" NormalCss SortDescCss"></em></th>
                    <th style="cursor: default;">已报班级<em class=" NormalCss SortDescCss"></em></th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody id="UserList" class="table table-bordered table-hover">
                <form action="{{ url_path }}">
                    <input type="submit"style="float: right">
                    <input type="text" name="search" style="float: right">
                </form>
                <form action="/crm/piliang/" method="post">

                    &nbsp; &nbsp; &nbsp; <select name="choi" id="">
                    <option value="a">公户转私户</option>
                    <option value="b">私户转公户</option>
                    &nbsp; &nbsp; &nbsp;


                    {% for i in cus_obj_lis %}
                        <tr>
                            <td class="editsquare">
                                <input type="checkbox" name="{{ forloop.counter }}" value="{{ i.pk }}"
                                       style="display: none">
                            </td>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ i.id }}</td>
                            <td>{{ i.qq }}</td>
                            <td>{{ i.qq_name }}</td>
                            <td>{{ i.name }}</td>
                            <td>{{ i.birthday }}</td>
                            <td>{{ i.phone }}</td>
                            <td>{{ i.source }}</td>
                            <td>{{ i.course }}</td>
                            <td>{{ i.class_type }}</td>
                            <td>{{ i.customer_note }}</td>
                            <td>{{ i.show_status }}</td>
                            <td>{{ i.last_consult_date }}</td>
                            <td>{{ i.next_date }}</td>
                            <td>{{ i.consultant }}</td>
                            <td>{{ i.introduce_from }}</td>
                            <td>
                                {% for class in i.class_list.all %}
                                    {{ class }}
                                {% endfor %}

                            </td>
                            <td>
                                <button class="btn btn-info aaa" value="{{ i.pk }}">删除</button>


                            </td>
                            <td><a href="{% url 'edit_customer' i.pk %}" style="color: white">
                                <button type="button" class="btn btn-info">修改</button>
                            </a></td>
                            <td>
                                <button class="btn btn-info bbb" value="{{ i.pk }}">建立关系</button>
                            </td>
                        </tr>

                    {% endfor %}
                    <button class="planniu">提交</button>
                </select>

                </form>
                </tbody>
            </table>
        </div>
    </div>
{#    <nav aria-label="Page navigation">#}
{#        <ul class="pagination" style="position: relative">#}

{#            {% if page_num == 1 %}#}
{#                <li class="disabled">#}
{#                    <a aria-label="Previous">#}
{#                        <span aria-hidden="true">&laquo;</span>#}
{#                    </a>#}
{#                </li>#}
{#            {% else %}#}
{#                <li>#}
{#                    <a href="?page={{ page_num|add:-1 }}" aria-label="Previous">#}
{#                        <span aria-hidden="true">&laquo;</span>#}
{#                    </a>#}
{#                </li>#}
{#            {% endif %}#}
{##}
{#            {% endfor %}#}
{#            {% if page_num == max_page %}#}
{#                <li class="disabled">#}
{#                    <a aria-label="Next">#}
{#                        <span aria-hidden="true">&raquo;</span>#}
{#                    </a>#}
{#                </li>#}
{#            {% else %}#}
{#                <li>#}
{#                    <a href="?page={{ page_num|add:1 }}" aria-label="Next">#}
{#                        <span aria-hidden="true">&raquo;</span>#}
{#                    </a>#}
{#                </li>#}
{#            {% endif %}#}


{#        </ul>#}
{#    </nav>#}
        <nav aria-label="Page navigation">
        <ul class="pagination">
            <li><a href="?page=1">首页</a></li>
            {{ page_html|safe }}
            <li><a href="?page={{ max_page }}">尾页</a></li>
            <li style="position: absolute;right: -750px">
                <form action="">
                    <input type="text" name="page" style="height: 35px;width:200px;border-color: red">
                    <button>跳转</button>
                </form>
            </li>
        </ul>
    </nav>

    <script src="{% static 'js/jquery.min.js' %} "></script>
    <script>
        $('.aaa').click(function () {
            console.log('777');
            console.log($(this).val());
            $.ajax({
                url: '/crm/del_abc/',
                type: 'post',
                data: {
                    username: $(this).val()
                },
                success: (res) => {
                    $(this).parent().parent().remove()
                    console.log(res)
                }
            })
        });

        $('.bbb').click(function () {
            $.ajax({
                url: '/crm/add_my_customer/',
                type: 'post',
                data: {
                    obj_id: $(this).val()
                },
                success: (ret) => {
                    $(this).parent().parent().remove()
                }
            })
        })
    </script>
    <script>


        $('.cliedit').click(function () {
            console.log('***');
            $('.editsquare').children().css('display','block');
        });


    </script>
{% endblock %}

liupicrm/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
<div class="login-container">
    <h1>ShareLink</h1>
    <div class="connect">
        <p style="left: 0%;">Link the world. Share to world.</p>
    </div>
    <form action="" method="post" id="loginForm" novalidate="novalidate">
        {% csrf_token %}
        <div>
            <input type="text" name="username" class="username valid" placeholder="用户名" autocomplete="off" value=""
                   aria-required="true" aria-invalid="false">{{ error }}
        </div>
        <div>
            <input type="password" name="password" class="password" placeholder="密码" oncontextmenu="return false"
                   onpaste="return false">
        </div>
        <button id="submit" type="submit">登 陆</button>
    </form>

    <a href="{% url 'reg' %}">
        <button type="button" class="register-tis">还有没有账号？</button>
    </a>
</div>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/common.js' %}"></script>

<script src="{% static 'js/supersized.3.2.7.min.js' %}"></script>
<script src="{% static 'js/supersized-init.js' %}"></script>

<script src="{% static 'js/jquery.validate.min.js' %}"></script>
</body>
</html>

liupicrm/templates/reg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
<div class="login-container">
    <h1>ShareLink</h1>
    <div class="connect">
        <p style="left: 0%;">Link the world. Share to world.</p>
    </div>
    <form action="" method="post" id="loginForm" novalidate="novalidate">
        {% csrf_token %}
        <div>
            {{ regform.username }}{{ regform.username.errors.0 }}
        </div>
        <div>
            {{ regform.password }}
            {{ regform.password.errors.0 }}
        </div>
        <div>
            {{ regform.re_password }}
            {{ regform.re_password.errors.0 }}
        </div>
        <div>
            {{ regform.name }}
            {{ regform.name.errors.0 }}
        </div>
        <div>
            {{ regform.mobile }}
            {{ regform.mobile.errors.0 }}
        </div>
        <div>
            {{ regform.department }}
            {{ regform.department.errors.0 }}
        </div>
        <button id="submit" type="submit">注册</button>
    </form>

    <a href="{% url 'login' %}">
        <button type="button" class="register-tis">已有账号？</button>
    </a>
</div>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/common.js' %}"></script>

<script src="{% static 'js/supersized.3.2.7.min.js' %}"></script>
<script src="{% static 'js/supersized-init.js' %}"></script>

<script src="{% static 'js/jquery.validate.min.js' %}"></script>
</body>
</html>